### ISSUE TITLE
win32 portion of this module is absolute jank

### ISSUE THREAD

**Issue by trollcop** [tomas/network#49] opened 2024-10-09 16:00 UTC
besides relying on broken unicode functionality of [tomas/wmic/#25](https://github.com/tomas/wmic/issues/25) the code is just broken. os.networkInterfaces() returns basic info about the adapter, INCLUDING its mac address. this should be the key for the remainder of WMI queries, 

but for some reason `get_wmic_ip_value` uses WMI calls (again) to get MACAddress based on NetConnectionID (nicname) which is garbled due to above bug and fails, and thus fails to obtain additional information such as `DefaultIPGateway` and `IPSubnet` etc. [when network adapter name is not-ASCII]

i understand that "free" and "opensores" node modules generally come with no warranty, but like, at least think through why things are done this way and maybe think of some optimizations to the process.

**Comment by tomas** [comment] 2024-10-09 19:43
I'm not sure what the problem is, but it looks like a problem in the wmic module and not in this one. Thus, I'm closing this issue.

**Closed as completed by tomas** 2024-10-09 19:43 UTC

**Comment by trollcop** [comment] 2024-10-09 21:41
i opened this to start a discussion about fixing the logic within win32 portion of this module. the wmic issue is adjacent to this one, but not completely related.

WMI calls are expensive, calls to wmic.exe even more so - any effort to minimize them thus should be appreciated.

my current concern is the part where netconnectionid (adapter friendly name) is used to lookup board mac address, when this information is already available in the structure returned by os.networkInterfaces. besides the encoding issue, i think it's not a very good idea to use user-changeable adapter name to look up details, especially when it requires an extra WMI call that can be avoided.

**Comment by tomas** [comment] 2024-10-09 21:49
As I said in the linked PR, I haven't looked at this code (nor wmic's) for quite a while so there's definitely room for improvement. I built this package a decade ago and used wmic because there wasn´t any other way of getting that information, but I assume that must have changed by now.

I'll be happy to merge any PRs that provides an alternate solution, but I can't implement it myself for the simple reason that I don't even have a modern windows PC where to test the implementation. :)

**Comment by trollcop** [comment] 2024-10-09 22:04
yes, wmic in general is going to get obsoleted, but that's still a few years in the future. the current issue is what i outlined above and in reply to your close comment, and still needs to be fixed.
